name: flutter_application_2
description: A new Flutter project.
publish_to: 'none' # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"  # Ensure compatibility with Dart 3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Updated to a compatible version
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/  # Correct asset path; make sure to use the correct folder name


